server {
    listen 80;
    server_name _; # Aceita requisições de qualquer IP ou domínio

    # Pasta onde o Docker vai colocar os arquivos do build do Vite
    root /usr/share/nginx/html;
    index index.html;

    # Regra principal para SPA (React/Vite)
    location / {
        # Tenta achar o arquivo exato ($uri).
        # Se não achar, tenta achar a pasta ($uri/).
        # Se não achar nenhum dos dois, manda para o index.html
        try_files $uri $uri/ /index.html;
    }

    # (Opcional) Regra de otimização: Cache para arquivos estáticos gerados pelo Vite
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff|woff2|eot|ttf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}